### ISSUE TITLE
Comskip endless loop ?

### ISSUE THREAD

**Issue by jluke1** [erikkaashoek/Comskip#102]
Mac os 10.13.4 Eyetv 3.6.9.
Comskip hangs in loop. Probably due to corrupted live recording. Start of errors
from log.

Retry=0 at frame=134862, time= 5395.32 seconds
Positioning file failing with pts=2516.28
Positioning file failing with pts=2516.32
Positioning file failing with pts=2516.36
Positioning file failing with pts=2516.40
Positioning file failing with pts=2516.44
Positioning file failing with pts=2516.48
Positioning file failing with pts=2516.52
Positioning file failing with pts=2516.56

Killing the process leaves a partially marked file.

All the same thanks for wonderful program that makes commercial TV watchable.

jluke

**Comment by erikkaashoek** [comment]
Indeed a positioning problem due to corrupt file.
If you do not use live tv processing you can set
retries=0
to eliminate this problem.

**Comment by jluke1** [comment]
Thanks will try. Have not been able to use live tv processing as comskip
crashes out before end, probably for similar reasons. This messes up
Eyetv pointers requiring restart of program. Would be nice if Eyetv handled
errors better. Will look again for alternatives as Eyetv flakey with High Sierra.
I fear it has become abandonware.

Thanks again for excellent software.

John Luke
