### ISSUE TITLE
Release new version of Comskip

### ISSUE THREAD

**Issue by mprahl** [erikkaashoek/Comskip#103]
Could you please create a new GitHub release of Comskip? I package this for the Fedora RPM Fusion repos and I'm currently carrying a few patches from master to be able to build against the latest ffmpeg and would like to avoid doing this.

**Comment by erikkaashoek** [comment]
Is being tested.
Some small problems with the new ffmpeg and some of my test files do require some more work

**Comment by mprahl** [comment]
Any update on this?

**Comment by erikkaashoek** [comment]
SHould be done now, can you test?

**Comment by erikkaashoek** [comment]
Comskip now uses latest ffmpeg
