### ISSUE TITLE
Create a latest release

### ISSUE THREAD

**Issue by phunkyfish** [erikkaashoek/Comskip#109]
Useful when wanting to reference the current version as a dependency.

**Comment by erikkaashoek** [comment]
Please explain. I do not understand

**Comment by phunkyfish** [comment]
The last release was created on GitHub in 2017: 0.82.003

Would be good to have a 0.82.007 release.

**Comment by phunkyfish** [comment]
<img width="1118" alt="Screenshot 2019-09-15 at 19 24 32" src="https://user-images.githubusercontent.com/4601187/64925865-7c5a6d00-d7ee-11e9-9b5e-46c805c55f78.png">

**Comment by erikkaashoek** [comment]
Done

**Comment by phunkyfish** [comment]
Maybe the release name should also be 0.82.009?
