### ISSUE TITLE
just a suggestion for comskip on linux

### ISSUE THREAD

**Issue by raspo666** [erikkaashoek/Comskip#139]
what about the following for comskip on linux ?
--- comskip.c.orig      2021-11-13 18:39:09.219241152 +0100
+++ comskip.c   2021-11-13 18:37:37.151248689 +0100
@@ -13050,6 +13050,10 @@
     {
         Debug(1, "%s not found\n", searchexefile);
     }
+#else ifdef __linux__
+
+strcpy(inifilename,"/etc/comskip.ini");
+
 #endif
 }
edit: somehow this online editor stole the double underscores around "linux" ...

**Comment by tmm1** [comment]
Please send PR to propose code changes
