### ISSUE TITLE
Parameter "--cut" not working as expected

### ISSUE THREAD

**Issue by chises** [erikkaashoek/Comskip#153]
Hello ,

I try to cut the video file based on the commercial detection. Commercial detection is working. 
```
FILE PROCESSING COMPLETE  37522 FRAMES AT  2500
-------------------
1       426
22787   24397
27829   28703
37521   37522
```
Based on the ./comskip out there is a parameter that could fit my requirements:
`  --cut=<file>              CutScene file to use`

I try to remove the commercials from my video file with the created txt. file from above with following command:
```
/opt/Comskip/comskip --cut=/var/lib/hts/Bob\'s-Burgers-4.txt /var/lib/hts/video.mkv
Comskip 0.82.011, made using ffmpeg
Donator build
The commandline used was:
        /opt/Comskip/comskip
        --cut=/var/lib/hts/video.txt
        /var/lib/hts/video.mkv


Loading cutfile /var/lib/hts/video.txt as per commandline
No INI file found in current directory.  Searching PATH...
INI file found at comskip.ini
No INI file found anywhere!!!!
 0:24:42 - 38577 frames in 60.55 sec(637.11 fps), 1.00 sec(653.00 fps), 98%
39048 frames decoded in 61.10 seconds (639.08 fps)
Commercials were found.
```
But there is no modified video file in any folder. Any detailed documentation about the --cut parameter?

Thank you for any support or hint how to remove the commercials from the video file!

Best Regards
Michael Weber

**Comment by tmm1** [comment]
comskip does not remove commercials it only detects them

**Comment by chises** [comment]
Thank you. Is there any documentation about the --cut? I don't understand it.
But I got it, to modify the video file I will use ffmpeg.
