### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by Behinder** [erikkaashoek/Comskip#155]
- Last release build is from 2019
- Build from source fails on MacOS X

I'm trying to find some automated solution for cutting ads from lot of the files and comskip is not effective :( 
Documentation is old, some posts on forum are over 10 years old. If I run comskip from terminal on Macos neither `-w` nor  using *.txt file generated from previous comskip run as input to another run working. If separate windows for debug are only Windows feature it should be written somewhere explicitly. So I would really like to know what is the current status of the project.

Or maybe this is one of those rare cases when cutting manually ads from over 300 files takes less time than tuning comskip 👎 😢

**Comment by tmm1** [comment]
The source is open if you want to make improvements.

The gui was working last time I tried on macOS 

https://github.com/erikkaashoek/Comskip/pull/120

**Comment by Behinder** [comment]
Thats intresting in terms of GUI, I see Eric merged your commit in December 2021,apparently I am using comskip from Channels from August 2021 hence the problems. 
I noticed also your branch for ffmpeg 5.0 but you stated that binary is created without errors but not works correctly, can you say in what way it won’t work correctly?

**Comment by Behinder** [comment]
Unfortunately I see developers of ffmpeg in 5.1 introduced too many breaking changes, deprecating lot of stuff without clear guidance how to proceed. The main error is good example - why to remove `codec` from AVStream struct? Stream must have a codec so it's at best illogical.

**Comment by tmm1** [comment]
You can use #152 for ffmpeg 5+

**Comment by Behinder** [comment]
I'm still lost at using github when there are external forks publishung
changes. I admire people who are able to make such corrections because
reading 4.3 docs and understanding what was changed in 5 is huuuge pain.
I assume I have to checkout rcombs:separate-codec
<https://github.com/rcombs/Comskip/tree/separate-codec>?

**Comment by Behinder** [comment]
Ok I compiled without problems.Give this man an Oscar:) Now I do some testing
