### ISSUE TITLE
OSX Mac built not working

### ISSUE THREAD

**Issue by murraypetera** [erikkaashoek/Comskip#27]
I am working to resolve this but my Makefile experience is 15 years out of date :)

comskip.c:17:10: fatal error: 'argtable2.h' file not found
#include <argtable2.h>

tried 
make INCLUDES="-I/usr/local/opt/ffmpeg/include:-I./vendor:/usr/local/include" LIBS="-L/usr/local/opt/ffmpeg/lib" SHLIBS="-lavutil.ffmpeg -lavformat.ffmpeg -lavcodec.ffmpeg -largtable2"
no luck yet.

**Comment by tmm1** [comment]
You need to install libargtable2 as stated in the readme: https://github.com/erikkaashoek/Comskip#macosx

```
$ brew install argtable
```

**Comment by tmm1** [comment]
> SHLIBS="-lavutil.ffmpeg -lavformat.ffmpeg -lavcodec.ffmpeg

This is only valid on ubuntu precise when using the pavlyshko/precise ffmpeg ppa.

**Comment by tmm1** [comment]
> INCLUDES="-I/usr/local/opt/ffmpeg/include:-I./vendor:/usr/local/include"

This syntax is incorrect, it should either be `-Ipath:path:path` or `-Ipath -Ipath -Ipath`

**Comment by murraypetera** [comment]
Thanks!
It seems the -Ipath:path does not work for me. OS X 10.11 
make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

-Ipath -Ipath 

does work 

I used the following command to get the compile to work:

make INCLUDES="-I./vendor -I/usr/local/include" LIBS="-L/usr/local/lib"

**Comment by tmm1** [comment]
You're right, the `-Ipath:path` syntax is invalid.

On OSX, `-I/usr/local/include` and `-L/usr/local/lib` are implied and should not be necessary. Make sure you've updated your xcode cli to the latest version.

**Comment by murraypetera** [comment]
I just updated Xcode 
The commandline used was:
./comskip drwho.mpg

Segmentation fault: 11
No core file to look at.

The mpg plays with VLC.
-v gives no output

Any ideas?

**Comment by tmm1** [comment]
Did you run `ulimit -c unlimited`? You might need to create `/cores` as listed in https://developer.apple.com/library/mac/technotes/tn2124/_index.html#//apple_ref/doc/uid/DTS10003391-CH1-SECCOREDUMPS

Or you can try running under gdb like `gdb --args ./comskip file.mpg`

**Comment by fflewddur** [comment]
Just a heads up: I'm working on autotool-ing comskip to smooth out this build process and gracefully handle Windows, Mac OS X, and Linux build environments. Hopefully I'll have a pull request ready later this week.

**Comment by tmm1** [comment]
The project already builds on all three platforms with minimal fuss. I'm not a huge fan of autotools personally but I'll reserve judgement until I see the PR.

**Comment by murraypetera** [comment]
Building with the command above works for me but when I run it, it always Core. I have not had time to relearn gdb yet. No debug info comes out before it dies even with the level set high. Im on 10.11

**Comment by tmm1** [comment]
What does otool -L comskip say? Are you using homebrew for argtable and
ffmpeg?

**Comment by fflewddur** [comment]
You might want to try building from the autotools branch at https://github.com/fflewddur/comskip/tree/autotools. I just tested this on Mac OS X 10.11 with homebrew (install packages `argtable`, `autoconf`, `automake`, `libtool`, `pkg-config`, and `ffmpeg`), and it compiles and runs as expected. To build it, run `autogen.sh`, then `configure` and `make`.
