### ISSUE TITLE
Cross compile error bad instruction `int3'

### ISSUE THREAD

**Issue by schumi2004** [erikkaashoek/Comskip#30]
I'm doing a attempt to cross compile comskip for Synology (SynoCommunity) and ran into this issue.

/home/openelec/github/spksrc/toolchains/syno-alpine-5.2/work/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -c  -I/home/openelec/github/spksrc/spk/comskip/work-alpine-5.2/install//usr/local/comskip/include  -g -pipe -Wall -W -Wno-address -Wno-unused-parameter -Wno-unused-label -Wno-unused-result -O2 -DDONATOR -DPROCESS_CC   -I.  -o mpeg2dec.o mpeg2dec.c
{standard input}: Assembler messages:
{standard input}:2968: Error: bad instruction `int3'
make[3]: *** [mpeg2dec.o] Error 1

Any idea what could be wrong here?

**Comment by tmm1** [comment]
You should be able to comment out the offending line
