### ISSUE TITLE
Comskip appends asynchronous timestamps to some .edl files

### ISSUE THREAD

**Issue by essandess** [erikkaashoek/Comskip#32]
I noticed this problem about 6 months ago but never investigated: Comskip appends weird timestamp information to the end of some .edl files. For example, here are example timestamps:

> 93526.47	93650.13	0
9493537.68	93779.19	0
94303.31	94423.60	0
94704.88	94915.89	0
0.67	120.15	0

This really messes with mp4chaps. etc-comskip translates this .edl into the following mp4 chapters and inserts them into iTunes file, which affects Video playback.

> 00:00:00.000 Beginning
25:58:57.680 Chapter 1 End
26:02:59.190 Chapter 2 Start
26:11:43.310 Chapter 2 End
26:13:43.600 Chapter 3 Start
26:18:24.880 Chapter 3 End
26:21:55.890 Chapter 4 Start
00:00:00.670 Chapter 4 End
00:02:00.150 Chapter 5 Start

I can provide the .mpg file for this example if needed.

**Comment by erikkaashoek** [comment]
Yes please provide a download link

**Comment by essandess** [comment]
I can't thank you enough for all your hard work Erik.

I'll send two tarballs of very different content streams that exhibit this problem: an animated Archer episode and Gwen Ifil's Washington Week. Perhaps Comskip is distracted by tall stunning black women with truckasaurus hands?

These examples also show false negatives. The Archer .edl doesn't have any of the ads, and shows a variant of the problem -- the final time is well before the initial time.

> 93707.98	93738.45	0
93950.19	94121.10	0
94442.95	94759.90	0
95088.83	119.85	0

As a motivator, and this is true, one of the ads not marked by Comskip encourage people to put lemons in beer, which I believe is felony crime where you are.

The Gwen Ifil .edl is:

> 94349.59	94472.95	0
95218.83	95220.86	0
603.17	943.21	0

This is public tv with sponsor content at the start, but this example shows the general problem I've observed: a bunch of anomalous detections of very short duration clustered at the end.

The tarballs also contain the Comskip log file for reference.

**Comment by murraypetera** [comment]
Fruit in beer is a sin unless it is brewed in like the Belgians do.

I will try the updates and auto build this weekend. I still have not figured out how to strip the mpg of the commercials once identified. I tried ffmpeg but failed horribly. If any of you have succeed please post your scrip or commands. 



From my iPad

Peter Murray
murraypetera@gmail.com
+1 914-414-3727
AIM   : retepmurray
GAIM:murraypetera@gmail.com
http://www.linkedin.com/in/peteramurray
https://www.vizify.com/peteramurray 
http://martialartsofwestchester.com

**Comment by essandess** [comment]
Okay it was a Blue Moon ad, but still.

In our experience with [etv-comskip](https://github.com/essandess/etv-comskip) we found that it's a lot more reliable to leave in the ads and use helper software to skip through them. This is because as awesome as Comskip is, its false alarm/missed detection/alignment isn't perfect, so it avoids annoyances to leave the final adjustments to the user.

The helper software we use is the [ComSkipper](https://github.com/essandess/etv-comskip/tree/master/src/scripts/ComSkipper) script for EyeTV on OS X . On iOS devices the native Videos app honors mp4 chapter skipping imbedded with the mp4chaps command. This extends to external device control like Apple earphones and even steering wheel controls via Bluetooth, not that anyone will be watching tv on an iPhone while driving.

If you still want to strip commercials out of the stream, Elgato's Turbo.264 software honors .edl files and does this automatically, with the ability to hand-adjust the .edl yourself.

**Comment by murraypetera** [comment]
Blue moon or not, it is not acceptable.. 

My personal theory about the lemon in the beer is the following.. 
I was told that in Mexico they would serve a beer with a lemon wedge on the mouth of the bottle to keep the flies out. The american tourists would come down on vacation and did not understand this so they would push the lemon in the bottle…

This trickled back up to the states and the rest is a sad sad history of ruining beer.. not that any Mexican beer can be ruined with a lemon…but I digress. ;)

Im working to try the etv-comskip…as for ComSkipper running with wine.. not so keen on this but may try it..

My next challenge is DRM stripping from MPEG2 which some of my channels have i.e. FX, HBO which are preventing me from viewing via. Plex.. 

Do you have a strategy for this?

Thanks again

**Comment by essandess** [comment]
I'm still refactoring etv-comskip for the version1.0 release. Thanks to Erik's appearance on GitHub, etv-comskip will no longer use wine. I'm mostly done, but want to see what Erik thinks of the autotools pull request and think about a few install options. But it's all working if you know how to hand configure a few steps. Btw, ComSkipper is just a python script running under a py2app OS X app—no wine ever used.

Your other question deserves a whole other thread. In short, HDCP is a [broken technology](http://www.howtogeek.com/208917/htg-explains-how-hdcp-breaks-your-hdtv-and-how-to-fix-it/), and is trivial to circumvent with a $20 HDMI splitter.

**Comment by tmm1** [comment]
> I still have not figured out how to strip the mpg of the commercials once identified. I tried ffmpeg but failed horribly.

If you put `output_ffsplit=1` in your comskip.ini, you can do the following:

```
$ ffmpeg -seek_timestamp 1 -i video.ts $(cat video.ffsplit)
$ ffmpeg -i concat:segment0.ts|segment1.ts|segment2.ts video_stripped.ts
```

Or, if you want to leave the commercials in but add chapter markers for video players use `output_ffmeta=1`:

```
$ ffmpeg -i video.ffmeta -i video.ts video.mkv
```

(This should probably go in the readme or similar document.)

**Comment by essandess** [comment]
Erik's latest [commit](https://github.com/erikkaashoek/Comskip/commit/900f60774fff75181b5e1d83e2bbd5a2d319371b) fixes the issue for me. The .edl timestamps in the two test streams are now correct:

> 60.46	90.89	0
302.64	473.51	0
795.39	915.48	0
1034.00	1112.34	0
1441.27	1576.91	0

> 0.00	123.36	0
