### ISSUE TITLE
Comskip binary not statically linked

### ISSUE THREAD

**Issue by essandess** [erikkaashoek/Comskip#33]
I'm trying to distribute a standalone comskip binary with [etv-comskip](https://github.com/essandess/etv-comskip/).

I just [discovered](https://github.com/essandess/etv-comskip/issues/60) that the comskip binary I compile is dynamically linked to libraries that won't necessarily exist on user boxes:

> `otool -L comskip`
	/opt/local/lib/libargtable2.0.dylib (compatibility version 2.0.0, current version 2.8.0)
	/opt/local/lib/libavutil.54.dylib (compatibility version 54.0.0, current version 54.31.100)
	/opt/local/lib/libavformat.56.dylib (compatibility version 56.0.0, current version 56.40.101)
	/opt/local/lib/libavcodec.56.dylib (compatibility version 56.0.0, current version 56.60.100)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

This obviously breaks comskip for most people.

Is there a way to compile comskip into a standalone binary on OS X so that it doesn't rely on Macports or homebrew libraries? I hope I'm just missing a simple ./configure directive...

**Comment by tmm1** [comment]
Are you using ./configure --enable-static?

**Comment by essandess** [comment]
No. I just tried `./configure --enable-static` but that appeared to have the opposite effect -- tool -L shows a lot more libraries in the resulting binary.  FWIW, I do not see anything like -DENABLE_STATIC in the make commands.

Am I misinterpreting the result of otool? Here's what it says when I run `--enable-static`:

> $ `otool -L ./comskip`
./comskip:
	/opt/local/lib/libargtable2.0.dylib (compatibility version 2.0.0, current version 2.8.0)
	/opt/local/lib/libavformat.56.dylib (compatibility version 56.0.0, current version 56.40.101)
	/System/Library/Frameworks/QTKit.framework/Versions/A/QTKit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1255.1.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation (compatibility version 1.0.0, current version 2.0.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1255.1.0)
	/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.4.0)
	/System/Library/Frameworks/VideoDecodeAcceleration.framework/Versions/A/VideoDecodeAcceleration (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)
	/opt/local/lib/libxcb.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	/opt/local/lib/libxcb-shm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libxcb-xfixes.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libxcb-render.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libxcb-shape.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57336.10.29)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1404.13.0)
	/opt/local/lib/libSDL-1.2.0.dylib (compatibility version 12.0.0, current version 12.4.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/opt/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
	/opt/local/lib/libx264.142.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libvorbisenc.2.dylib (compatibility version 3.0.0, current version 3.11.0)
	/opt/local/lib/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	/opt/local/lib/libogg.0.dylib (compatibility version 9.0.0, current version 9.2.0)
	/opt/local/lib/libtheoraenc.1.dylib (compatibility version 3.0.0, current version 3.2.0)
	/opt/local/lib/libtheoradec.1.dylib (compatibility version 3.0.0, current version 3.4.0)
	/opt/local/lib/libspeex.1.dylib (compatibility version 7.0.0, current version 7.0.0)
	/opt/local/lib/libschroedinger-1.0.0.dylib (compatibility version 12.0.0, current version 12.0.0)
	/opt/local/lib/libopus.0.dylib (compatibility version 6.0.0, current version 6.0.0)
	/opt/local/lib/libopenjpeg.1.dylib (compatibility version 7.0.0, current version 7.0.0)
	/opt/local/lib/libmp3lame.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libmodplug.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/opt/local/lib/libfribidi.0.dylib (compatibility version 4.0.0, current version 4.5.0)
	/opt/local/lib/libglib-2.0.0.dylib (compatibility version 4601.0.0, current version 4601.1.0)
	/opt/local/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.4.0)
	/opt/local/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.1.0)
	/opt/local/lib/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/local/lib/libbluray.1.dylib (compatibility version 11.0.0, current version 11.0.0)
	/opt/local/lib/libass.5.dylib (compatibility version 7.0.0, current version 7.1.0)
	/opt/local/lib/libgnutls.28.dylib (compatibility version 70.0.0, current version 70.10.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
	/opt/local/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.2.0)
	/opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.6)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/opt/local/lib/libavcodec.56.dylib (compatibility version 56.0.0, current version 56.60.100)
	/opt/local/lib/libswresample.1.dylib (compatibility version 1.0.0, current version 1.2.101)
	/opt/local/lib/libavutil.54.dylib (compatibility version 54.0.0, current version 54.31.100)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

**Comment by essandess** [comment]
Is this[ Apple Developer](https://developer.apple.com/library/mac/qa/qa1118/_index.html) page relevant?

> Apple does not support statically linked binaries on Mac OS X.

Static linking to system binaries isn't allowed for compatibility, but all I need is static linking of the macports libraries.

**Comment by tmm1** [comment]
First make sure that ffmpeg static libs were built by macports. Is there a
libavcodec.a installed?

**Comment by essandess** [comment]
Yes. Macports put it in `/opt/local/lib/libavcodec.a`.

Note that comskip, but not ffmpeg, requires`libargtable2`, and this is missing from the comskip binary. This suggests to me that one of the compile/link commands in the make sequence is not configured to link `libargtable2` statically.

**Comment by tmm1** [comment]
> this is missing from the comskip binary

Hmm, what do you mean it is missing?

**Comment by tmm1** [comment]
There's a note in the README about static linking on OSX, with a link to https://dropline.net/2015/10/static-linking-on-mac-os-x/

**Comment by essandess** [comment]
By missing, I mean that the comskip binary I build has a dynamic link to these libraries, and are not linked statically within the comskip binary. I'll read a little more about how to do this on OS X. I'm still not sure if the is a configure && make issue or a compiler issue. Do you see what I see with the commands:

> autogen.sh
./configure --enable-static
make
otool -L comskip

**Comment by essandess** [comment]
> There's a note in the README about static linking on OSX, with a link to https://dropline.net/2015/10/static-linking-on-mac-os-x/

Wow what a major hack!—this copies `*.dylib` to `*.hidden`. Of course that breaks the autoconf tools used in the build… Thank you Apple.

I'll try to hide only the shared libraries necessary and see if that works. Is this actually what's necessary to distribute standalone binaries for OS X?

I have a better hack in mind that replicates what OS X does:

* Copy the shared libs required by the binary to the final distribution directory.
* Recompile the code with a binary that points to those shared libs.
* Distribute the binary with an Installer that puts everything in the right place.

How do I tell ./configure to use this distribution directory for make builds?

**Comment by tmm1** [comment]
> I'll try to hide only the shared libraries necessary and see if that works. Is this actually what's necessary to distribute standalone binaries for OS X?

Not necessarily to distribute, but to build a static binary yes.

You might also look into `install_name_tool` which will let you ship both the binary and the required libs together as a single bundle by "fixing" the paths to the libraries referenced in the binary.

**Comment by essandess** [comment]
`install_name_tool` is the [way too go](http://thecourtsofchaos.com/2013/09/16/how-to-copy-and-relink-binaries-on-osx/) here. The problem is that this results a large shared library dependency tree with dozens of commands that look like:

`install_name_tool -change /opt/local/lib/libswresample.1.dylib @executable_path/../lib/libswresample.1.dylib ../lib/libavcodec.56.dylib`

The only way to accomplish this reliably, especially through successive releases, is to write a Python script that automates all this. A GitHub project all of its own. Surely someone has done this already. I'll go poke around before doing it myself.

Please post if you know of an existing script.

**Comment by essandess** [comment]
A related issue: `./configure --enable-static` produces a `Makefile` without the target `comskip_gui`.

Is this expected behavior?

**Comment by essandess** [comment]
No one had written this so I created a new GitHub repository [matryoshka-name-tool](https://github.com/essandess/matryoshka-name-tool) to automatically handle shared library distributions using `install_name_tool`. Comskip alone with its aired library dependency tree requires 4294 calls to `install_name_tool` to create a distributable shared library, so there's no way this can be done by hand! I'll get back to testing a new binary plus shared library distribution soon.

**Comment by essandess** [comment]
This now works with shared libraries. There's a Makefile build example over at etv-comskip.
