### ISSUE TITLE
configure error building on ubuntu trusty

### ISSUE THREAD

**Issue by dnnyg33** [erikkaashoek/Comskip#36]
I successfully ran through these commands  
https://github.com/erikkaashoek/Comskip#ubuntu-trusty-1404  
Then attempted to build from git  
https://github.com/erikkaashoek/Comskip#building-from-github  
(I also installed the required GNU autotools)

Now when running ./configure i get this error:  
>configure: error: Package requirements (libavutil >= 54.7 libavformat >= 56.4 libavcodec >= 56.1) were not met:  
>Requested 'libavutil >= 54.7' but version of libavutil is 52.3.0  
>Requested 'libavformat >= 56.4' but version of libavformat is 54.20.4  
>Requested 'libavcodec >= 56.1' but version of libavcodec is 54.35.0  

But running `sudo apt-get install libavutil-dev` states that  
>"libavutil-dev is already the newest version."  

Same with the other two libraries. What am i missing here?  
I realize this is not an issue with the Comskip code, but possibly the configure script or at the very least it might be helpful to have some more clarification in the ReadMe->Setting up build environment section as to what other dependencies are necessary and where to get the required versions.  

Thanks

**Comment by gpulido** [comment]
Hello,
I'm facing the same problem.
Also if I execute ffmpeg it claims that have the right versions:

/usr/bin/ffmpeg 
ffmpeg version N-77455-g4707497 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      55. 11.100 / 55. 11.100
  libavcodec     57. 20.100 / 57. 20.100
  libavformat    57. 20.100 / 57. 20.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 21.101 /  6. 21.101
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

What I have to do to compile Comskip?

**Comment by mortax** [comment]
remind me later and i’ll share my configuration.

**Comment by gpulido** [comment]
Thank you!!, it would be awesome, I'm just trying to figure out how the cflags works and I'm a struggling a litte :)

**Comment by mortax** [comment]
just reread this thread and, unfortunately, i may not be able to help. i compiled on OS X after downloading and building everything locally (not using apt-get). let me know if you'd like to hear more about what i did.

**Comment by gpulido** [comment]
Hello,
I've been able to pass the configure stage when I realised thad the ffmpeg was installed on /opt/ffmpeg so I had just to add
export PKG_CONFIG_PATH=/opt/ffmpeg/lib/pkgconfig

The problem now is that it doesn't compile, seems to be a too old ffmpeg problem. So I'm just recompiling ffmpeg from scratch using https://gist.github.com/xdamman/e4f713c8cd1a389a5917
After that I will give Comskip a try again.
