### ISSUE TITLE
Relationship to http://forum.kodi.tv/showthread.php?tid=150084 ?

### ISSUE THREAD

**Issue by gdevenyi** [erikkaashoek/Comskip#38]
I've seen a linux release called comskip here, http://www.xilka.com/xilka/source/comskip-0.93i.tar.xz

It looks pretty stale compared to the recent updates here. It looks like from the copyright that it's a fork of an earlier source?

Have the changes in that version been integrated here?

**Comment by tmm1** [comment]
That's an old fork which lacked many newer comskip features and was eventually abandoned. The author decided to rewrite the project in C++ which meant none of the changes could be integrated back into the original comskip.

The latest version of comskip in this repo now has full MacOSX and Linux compatibility. No forks required.

**Comment by tmm1** [comment]
In fact that thread even points to this repo: http://forum.kodi.tv/showthread.php?tid=150084&pid=2101964#pid2101964

**Comment by gdevenyi** [comment]
Cheers, I didn't actually read the thread just the main post. Thanks for your effort on this. I intend to do my best to contribute to the project.
