### ISSUE TITLE
"frame" used without ever being allocated in DetectCommercials

### ISSUE THREAD

**Issue by gdevenyi** [erikkaashoek/Comskip#39]
I'm running some static analysis using clang's scan-build tool (PR coming soon with some memory leak fixes and other things)

It reports a NULL pointer dereference in DetectCommercials referring to "frame", from my reading of the code, I see no signs of allocating or otherwise creating frame within the scope of DetectCommercials.

I think this is a bug?

https://github.com/erikkaashoek/Comskip/blob/master/comskip.c#L3075-L3243

**Comment by gdevenyi** [comment]
Specifically reporting
"Dereference of NULL pointer" on
https://github.com/erikkaashoek/Comskip/blob/master/comskip.c#L3220

**Comment by erikkaashoek** [comment]
Using "frame" was an option in early versions but now always used and filled.
So this is not a error
