### ISSUE TITLE
[REQUEST]: Update instructions for 14.04 and static compiles

### ISSUE THREAD

**Issue by stuckless** [erikkaashoek/Comskip#48]
I've created a [docker image](https://github.com/stuckless/sagetv-dockers/tree/master/comskip-build) for building comskip, and I can get it to work for 15.04, but, when I tried to build a 14.04 docker image, the compile fails.  It seems to be related to the version ffmpeg, I think.  Just wondering if the 14.04 version has been tested in a while?  I did get 14.04 to compile by pulling in my own ffmpeg and compiling/installing that as part of the process.

Also, I've tried to use the option to create a static binary.  Just wondering if you have any samples that work for you in terms of creating a static binary.  I tried for many hours to hand craft the various LIBS variables, but, in the end I threw in the towel :(

Thanks for all the great work... I've been running comskip donator version (using wine) for several years now... It's great to finally be running this on my Linux media server, natively.

**Comment by stuckless** [comment]
This isn't 14.04 specific, but I did manage to get a static compile working... I have docker image that I use for building comskip + latest ffmpeg.

https://github.com/stuckless/sagetv-dockers/tree/master/comskip/comskip-build-static

The end result is a 80M executable that is statically linked.

**Comment by erikkaashoek** [comment]
Is the 80M size after stripping off the symbols?

**Comment by stuckless** [comment]
I don't do anything, specific to remove symbols... not sure how to do that... So the 80m is the filesize after issuing the following commands...

```
# build static
rm -rf Comskip
git clone https://github.com/erikkaashoek/Comskip.git
pushd /build/Comskip
./autogen.sh
PKG_CONFIG_PATH=/build/comskipbuild/install/lib/pkgconfig ./configure --sysconfdir=/build/binaries/static/etc --bindir=/build/binaries/static/bin --enable-static
make
make install
popd
```

**Comment by stuckless** [comment]
So, after using copying comskip to comskip.test and running
```
strip --strip-all comskip.test
```
```
-rwxrwxr-x 1 seans seans 83M Nov 13 09:55 comskip
-rwxrwxr-x 1 seans seans 19M Dec 20 07:42 comskip.test
```
my files size went form 83m to 19m that's quite the savings.... I guess, since I don't know anything about what strip does... is the 19m binary the same as the 83m binary in that it will work/perform that same way?  (thanks)

**Comment by erikkaashoek** [comment]
It will perform in exactly the same way
strip remove debugging info

**Comment by stuckless** [comment]
@erikkaashoek thanks for that tip... I'll update the docker image to create stripped output as well.  And especially thanks to your for work on this.

**Comment by essandess** [comment]
@stuckless FWIW, when I first created a BSD build for macOS, I cursed Apple for not supporting static builds. After some experience with this and building a dynamic binary with this [Makefile](../../../essandess/etv-comskip/blob/master/Makefile), I've learned to appreciate the efficiencies that come with dynamic binaries, and prefer them now. I'd suggest considering whether a static build is something you really, really want.

**Comment by stuckless** [comment]
@essandess - Thanks... I'm really indifferent, myself... But I'm a long time linux user, so, ideally I'd rather use shared libraries... the issue that I run into, is that, many people are trying to get this working, on linux using SageTV (which is the PVR software that I support), and as such, providing a static binary that just works... minimizes my support ;)

**Comment by essandess** [comment]
> minimizes my support

I get that. I have found that distributing dynamic compiles along with an associated `./lib` directory filled with dependent shared libraries minimizes my support. You only have to make sure that you have permission to share the libraries this way, and this is possible for comskip.
