### ISSUE TITLE
Install process on Debian 8.4?

### ISSUE THREAD

**Issue by villasenor** [erikkaashoek/Comskip#53]
Hello! Could you add to the readme what the process would be on Debian 8.4? I'm having a terrible time trying to get it to install! Thanks in advance :)

**Comment by delmartechdude** [comment]
Or Debian 8 in general :)

**Comment by shottothedome** [comment]
I just installed in debian with only an issue during make listed here: https://github.com/erikkaashoek/Comskip/issues/74
