### ISSUE TITLE
Won't install on Ubuntu 16.04

### ISSUE THREAD

**Issue by greekislandlover** [erikkaashoek/Comskip#55]
I'm looking to run Comskip on my Ubuntu server that has Plex and TVheadend running. I notice the Linux installatio instructions stop at Vivid Vervet. I have tried running with these instructions, but ./Configure falls over with the following error:-

./configure: line 3789: PKG_PROG_PKG_CONFIG: command not found
./configure: line 3793: syntax error near unexpected token `argtable2,'
./configure: line 3793: `PKG_CHECK_MODULES(argtable2, argtable2 >= 2.12)'

**Comment by arcanez** [comment]
do you have **libargtable2-0** and **libargtable2-dev** installed?

**Comment by Greg2dot0** [comment]
Jumping in here because I have the exact same issue. 

Yes, libargtable2-0 and libargtable2-dev are both installed.

**Comment by stuckless** [comment]
I created a docker container that I use for building comskip.  I end up creating a very large statically linked binary so that I don't have to worry about dependencies... but, there is also a docker container that builds it normally.  My post is here.... https://github.com/erikkaashoek/Comskip/issues/48#issuecomment-236907072

I had issues going beyond 15.04 (which is why I created the static version).   I use comskip in my SageTV Docker for unRAID setup.

**Comment by Mr-Dave** [comment]
You may want to validate that you have pkgconf installed.  <code> sudo apt-get install pkgconf</code>

**Comment by Greg2dot0** [comment]
That was definitely an issue and got me past the above error, but now it would seem that I have some issue with ffmpeg.

configure: error: Package requirements (libavutil >= 54.7 libavformat >= 56.4 libavcodec >= 56.1) were not met:

but, if I run ffmpeg, I get this:
```
ffmpeg version 2.8.10-0ubuntu0.16.04.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  **WARNING: library configuration mismatch**
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

After doing some research, I went and attempted to compile ffmpeg from scratch which got rid of the mismatch error above but still comes up with the same error.

**Comment by Mr-Dave** [comment]
If you do a custom ffmpeg build, you will usually need to give a hint to pkgconf of where you installed it.  This is a illustration of how to give that hint (your install location will probably vary and will need to be adjusted) <code>PKG_CONFIG_PATH=/home/greg/ffmpeg_build/lib/pkgconfig ./configure </code>  It may also be possible to do this with a configure option but I didn't look since this worked for me.

**Comment by Greg2dot0** [comment]
Finally getting back around to looking at this again. The above got me to a point where I could execute the configure, but now the make is throwing all sorts of errors. Seem to be related to display...I'm running headless, but don't see any make options not to configure the GUI. (I could totally be barking up the wrong tree here, but figured I'd at least try to analyze). But, at least I'm getting closer and learning a lot.

`~/Comskip$ make
gcc -g -O2 -mtune=generic    -o comskip comskip-comskip.o comskip-mpeg2dec.o comskip-platform.o comskip-video_out_dx.o ccextratorwin/comskip-608.o ccextratorwin/comskip-ccextractor.o ccextratorwin/comskip-encoding.o ccextratorwin/comskip-general_loop.o ccextratorwin/comskip-myth.o -largtable2   -L/home/greg/ffmpeg_build/lib -lavformat -lavcodec -lXv -lvdpau -lva-x11 -lva-drm -lva -lxcb-shm -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -lSDL2 -Wl,--no-undefined -lasound -lpulse-simple -lpulse -lsndio -lX11 -lXext -lXcursor -lXinerama -lXi -lXrandr -lXss -lXxf86vm -lwayland-egl -lwayland-client -lwayland-cursor -lxkbcommon -lx265 -lstdc++ -lrt -lx264 -ldl -lvpx -lpthread -lvorbisenc -lvorbis -ltheoraenc -ltheoradec -logg -lopus -lmp3lame -lfdk-aac -lass -lharfbuzz -lfontconfig -lexpat -lfribidi -lfreetype -lpng12 -lz -pthread -lswresample  -lavutil -lm    -lpthread -lm
/home/greg/ffmpeg_build/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_free':
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:899: undefined reference to `XCloseDisplay'
/home/greg/ffmpeg_build/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:929: undefined reference to `XOpenDisplay'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:934: undefined reference to `vaGetDisplay'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:941: undefined reference to `XDisplayName'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:931: undefined reference to `XDisplayName'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:958: undefined reference to `vaGetDisplayDRM'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:929: undefined reference to `XOpenDisplay'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:931: undefined reference to `XDisplayName'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vaapi.c:936: undefined reference to `XDisplayName'
/home/greg/ffmpeg_build/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_create':
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vdpau.c:431: undefined reference to `XOpenDisplay'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vdpau.c:437: undefined reference to `XDisplayString'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vdpau.c:439: undefined reference to `XDefaultScreen'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vdpau.c:439: undefined reference to `vdp_device_create_x11'
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vdpau.c:433: undefined reference to `XDisplayName'
/home/greg/ffmpeg_build/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_free':
/home/greg/ffmpeg_sources/ffmpeg/libavutil/hwcontext_vdpau.c:410: undefined reference to `XCloseDisplay'
collect2: error: ld returned 1 exit status
Makefile:457: recipe for target 'comskip' failed
make: *** [comskip] Error 1
`

**Comment by Greg2dot0** [comment]
SOLVED: Near as I can tell, it seems to indicate that there are some libraries missing from the makefile. I've had some success referencing:  https://stackoverflow.com/questions/38850260/errors-when-compiling-c-code-with-ffmpeg-library 
and updating the ComSkip Makefile to include:

LIBS = **-lX11** **-lva** **-lva-drm** **-lva-x11** -lm -lvdpau -lpthread

**Comment by Greg2dot0** [comment]
(head-slap) Ok, after doing some digging, I think I figured out how to solve this much easier. I realize now that I'm running **headless** and many of the library issues were involving **ffplay**. In the build, I simply add a  _--disable-ffplay_ and that made the rest of the exercise easy...no need to add extra libraries.

**Comment by albertcard** [comment]
I'm not sure if we're at the same place. Are you saying you added _--disable-ffplay_ when you performed the './configure' step for Comskip installation? I tried adding that flag but it isn't recognized:

```
$ ./configure --disable-ffplay
configure: WARNING: unrecognized options: --disable-ffplay
```

**Comment by Greg2dot0** [comment]
> I'm not sure if we're at the same place. Are you saying you added --disable-ffplay when you performed the './configure' step for Comskip installation? I tried adding that flag but it isn't recognized:

No, I used that when I built FFMPEG. https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

Once I cleared up the ffmpeg errors, the rest worked ok.

Hope this helps.

**Comment by jschwalbe** [comment]
`sudo apt-get install libavformat-dev`
seemed to fix it for me.

**Comment by mprahl** [comment]
This is how I installed it on Ubuntu 16.04:
```
apt-get install -y git build-essential libargtable2-dev libsdl1.2-dev libavformat-dev autoconf libtool
git clone git://github.com/erikkaashoek/Comskip
cd Comskip
./autogen.sh
./configure
make
```

This produces a binary named `comskip` in the `Comskip` folder.

**Comment by mjbrowns** [comment]
FYI one thing I've learned is to use git clone --depth=1

That makes it pull down only the latest version of each file, instead of cloning the entire repo.  It's MUCH faster especially for projects that have.

Another thing I've done nowadays is I've moved to using docker for development - so I have posted on dockherhub an ubuntu environment with a lot of build tools installed - see [here](https://hub.docker.com/r/mbrown/buildenv/) if you are interested.

**Comment by MCTyler** [comment]
> This is how I installed it on Ubuntu 16.04:
> 
> ```
> apt-get install -y git build-essential libargtable2-dev libsdl1.2-dev libavformat-dev autoconf libtool
> git clone git://github.com/erikkaashoek/Comskip
> cd Comskip
> ./autogen.sh
> ./configure
> make
> ```
> This produces a binary named `comskip` in the `Comskip` folder.

Works in 18.04 too! Thanks!
