### ISSUE TITLE
Error with make on raspberry pi 3

### ISSUE THREAD

**Issue by pbathuk** [erikkaashoek/Comskip#56]
Hi,
Quite new to the whole Linux OS, however I have managed to get ffmpeg and a few other things running on my RPi3, however when I try to build comskip I get the following error :

pi@raspberrypi:~/Comskip $ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for fmax in -lm... yes
checking for sem_post in -lpthread... yes
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking whether host is win32... no
checking whether host is darwin... no
checking whether to enable donator features... yes
checking whether to build a statically linked binary... no
checking whether to build with debugging options enabled... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for argtable2... yes
checking for ffmpeg... yes
checking for sdl... yes
checking whether to build the graphical user interface... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
pi@raspberrypi:~/Comskip $ make
gcc -DPACKAGE_NAME=\"Comskip\" -DPACKAGE_TARNAME=\"comskip\" -DPACKAGE_VERSION=\"0.81.089\" -DPACKAGE_STRING=\"Comskip\ 0.81.089\" -DPACKAGE_BUGREPORT=\"https://github.com/erikkaashoek/Comskip/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"comskip\" -DVERSION=\"0.81.089\" -DHAVE_LIBM=1 -DHAVE_LIBPTHREAD=1 -I.  -Wall  -I/usr/local/include  -DPROCESS_CC -DDONATOR  -g -O2 -mtune=generic  -MT comskip-mpeg2dec.o -MD -MP -MF .deps/comskip-mpeg2dec.Tpo -c -o comskip-mpeg2dec.o `test -f 'mpeg2dec.c' || echo './'`mpeg2dec.c
gcc: error: unrecognized argument in option ‘-mtune=generic’
gcc: note: valid arguments to ‘-mtune=’ are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a8 cortex-a9 cortex-m0 cortex-m0plus cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 cortex-r7 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 strongarm1110 xscale
Makefile:532: recipe for target 'comskip-mpeg2dec.o' failed
make: *** [comskip-mpeg2dec.o] Error 1
pi@raspberrypi:~/Comskip $

Not knowing what todo I'm a little stumped as to how to do fix. 
Any help gratefully received 

Thanks
Phil

**Comment by tmm1** [comment]
Change the Makefile to remove `-mtune=generic`

**Comment by tmm1** [comment]
cc @gdevenyi

**Comment by pbathuk** [comment]
I have changed (using nano Makefile) mtune=generic with mtune=cortex-a53 
Processing as we speak. Will see what it says

**Comment by pbathuk** [comment]
It would appear to have worked. :) QQ : do I run :
./Configure --enable-static
Make
Sudo make install

To have comskip so I can run it from anywhere?

**Comment by tmm1** [comment]
You can check `ldd comskip` to see if it is linked to any libraries which will be required to run it.

**Comment by pbathuk** [comment]
Brilliant, thanks so much.
All sorted now. 
Will copy my ini from Windows
