### ISSUE TITLE
Error compiling on 64 bit Win 10 due to undefined GWL_USERDATA

### ISSUE THREAD

**Issue by ImCoKeMaN** [erikkaashoek/Comskip#57]
I got an error when building due to an error in the file video_out_dx.c 

The following lines need to be adjusted as to use the new Ptr calls:
352          instance = (dx_instance_t *) GetWindowLong (hwnd, GWL_USERDATA);
544     SetWindowLong (instance->window, GWL_USERDATA, (LONG) instance);

Proposed Changes:
352          instance = (dx_instance_t *) GetWindowLongPtr (hwnd, GWLP_USERDATA);
544     SetWindowLongPtr (instance->window, GWLP_USERDATA, (LONG) instance);

**Comment by tmm1** [comment]
Fixed in ff8bc01
