### ISSUE TITLE
Pre compiled Windows version / full step by step guide

### ISSUE THREAD

**Issue by pbathuk** [erikkaashoek/Comskip#58]
Hi, 
I have this setup and working on my raspberry Pi, however I am wanting to get it setup on my win 10 machine as well, I have tried to follow the guide in the readme, but ended up getting lost and ffmpeg would not compile, or when it did I could not understand what else I needed and where.
Therefore does anyone have a pre compiled version for win 10 for download OR is there a full step by step setup guide (YouTube etc) which would lead me to the correct answer?
Some of the issues I was facing :
Kept saying pkg_ not available (even though I installed it)
I did not understand the paths section, what am i doing here & why?
I downloaded msys2 but there was no .Bat for the minsys64 so got really lost.

Cheers for any help :)

Phil

**Comment by erikkaashoek** [comment]
Go to http://www.comskip.org/ to find a pre-compiled windows version
Erik.

**Comment by pbathuk** [comment]
Thanks. So just to confirm : http://www.kaashoek.com/donators/ is the latest version? (I paid the $10 a while ago to get access)
I can see the latest version (already installed on my machine is from march 2016)

**Comment by erikkaashoek** [comment]
Yes

**Comment by pbathuk** [comment]
Perfect. I was under the assumption that this was a different fork / newer.. thanks for the info :)

**Comment by pbathuk** [comment]
i am trying to register for the forum, but the question at the bottom wont accept any answers i enter! do you have a workaround? 
wanting to post in there to get some advise on how to improve my comskip as only getting 35fps on h.264 files

**Comment by erikkaashoek** [comment]
Try the second part of the name of the software we are discussing there
