### ISSUE TITLE
Permission to distribute

### ISSUE THREAD

**Issue by mjbrowns** [erikkaashoek/Comskip#61]
First off, great work on Comskip!  

I've been working on a docker service that combines plex and comskip (and a few other things) to produce a simple to use plex implementation complete with automatic commercial marking/cutting and transcoding.

I've published my build files on github [here](http://github.com/mjbrowns/plexpost).

What I provide at this point is a dockerfile and a set of scripts that will build a container that includes comskip built directly from your github repo.  What I'd really like to do is set up an automated build on the dockerhub for a complete container that includes a pre-built comskip.

Before I do that I wanted to make sure it was okay with you.  I'm not really sure what license you provide the source code, but I figure its best to make sure its okay with you before I proceed.

**Comment by erikkaashoek** [comment]
OK to do so.

I would appreciate if you could mention my "contribution" and point people to http://www.comskip.org/  for active support and donations

**Comment by mjbrowns** [comment]
Already done :)

Thanks!

Regards,

Mitch Brown
330-391-0447 (mobile)
mitch@mjbrowns.com
-- Sent from my mobile phone
