### ISSUE TITLE
Creation of Comskip for Mac OS Sierra

### ISSUE THREAD

**Issue by rnbarg** [erikkaashoek/Comskip#63]
Instructions provided in readme re: Mac 

I’m not a programmer, but I have technical skills and desire.  Installed Xcode command-line tools and homebrew - see in red.

When I ran $ brew install autoconf automake libtool pkgconfig argtable ffmpeg sdl  I got te error below. Can you advise further. I am fine running com skip manually on a file for now vs. integating into kmttg. 

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  http://docs.brew.sh/Analytics.html

==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    http://docs.brew.sh
DOM-4SB9JC2-LT:~ RichardMac$ $ brew install autoconf automake libtool pkgconfig argtable ffmpeg sdl
-bash: $: command not found
DOM-4SB9JC2-LT:~ RichardMac$

**Comment by essandess** [comment]
See this [Makefile](../../../../essandess/etv-comskip). It uses Macports, but the translation to homebrew is straightforward.

**Comment by tmm1** [comment]
You copied the $ as part of your command. The command starts with brew.
