### ISSUE TITLE
Debian 8 - make build failing

### ISSUE THREAD

**Issue by shottothedome** [erikkaashoek/Comskip#74]
I'm trying to build comskip for debian 8.x. I've gotten everything done up to the make process. I'm getting an error during make.

`gcc -g -O2    -o comskip comskip-comskip.o comskip-mpeg2dec.o comskip-platform.o comskip-video_out_dx.o ccextratorwin/comskip-608.o ccextratorwin/comskip-ccextractor.o ccextratorwin/comskip-encoding.o ccextratorwin/comskip-general_loop.o ccextratorwin/comskip-myth.o -largtable2  -lavutil -lavformat -lavcodec
/usr/bin/ld: comskip-mpeg2dec.o: undefined reference to symbol 'fmax@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:446: recipe for target 'comskip' failed
make: *** [comskip] Error 1
`
./config went through without a hitch once i got the needed dev files installed. Any ideas on what i need to fix here?

**Comment by tmm1** [comment]
Looks like you may need LDFLAGS=-lm

**Comment by shottothedome** [comment]
@tmm1 I added -lm to Makefile on line LDFLAGS=  after starting from scratch and I'm still getting the error. Is there something else I'm supposed to do with that setting? I see it showing up there now under the make error whereas it was not there before.

`make
gcc -g -O2   -lm -o comskip comskip-comskip.o comskip-mpeg2dec.o comskip-platform.o comskip-video_out_dx.o ccextratorwin/comskip-608.o ccextratorwin/comskip-ccextractor.o ccextratorwin/comskip-encoding.o ccextratorwin/comskip-general_loop.o ccextratorwin/comskip-myth.o -largtable2  -lavutil -lavformat -lavcodec
/usr/bin/ld: comskip-comskip.o: undefined reference to symbol 'sem_post@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:446: recipe for target 'comskip' failed
make: *** [comskip] Error 1
`

**Comment by tmm1** [comment]
Need "-lm-lpthread"

**Comment by shottothedome** [comment]
Thank you sir that worked. I changed line:
`LDFLAGS=
to
LDFLAGS= -lm -lpthread` in Makefile. I appreciate the help
