### ISSUE TITLE
HW Acceleration not Working (Nvidia)

### ISSUE THREAD

**Issue by arrmo** [erikkaashoek/Comskip#76]
Hi,

Running a build from current (Github) code, it doesn't seem like HW acceleration is working ... at least based on nvidia-smi on Linux, comskip is not calling cuda, and is providing no cuda load. Is this as expected? Yes, I did confirm that the configuration file (and command line, tried both) are enabling HW acceleration.

Thanks!

**Comment by tmm1** [comment]
Only a few specific hardware accelerators are supported. If you want to use a different one you woul need to add support in the code.

**Comment by arrmo** [comment]
NP, will definitely take a look! Any pointers on where this is called / used?

Thanks!
