### ISSUE TITLE
Debugwindow closes at end of run

### ISSUE THREAD

**Issue by mjbrowns** [erikkaashoek/Comskip#80]
I'm just starting to get going with show specific tuning and i'm attempting to leverage [the guide](http://www.kaashoek.com/files/debugwindow.htm) and I'm stuck at first base. 

Per the very first line in the guide:

```
When ComSkip is started with the –w or --debugwindow switch a graphics window will appear. Once finished Comskip will NOT automatically exit but has to be closed manually by killing the console window or by hitting ESCAPE. Do not use the debug window when Comskip is called automatically from GBPVR or other PVR software.
```

However for me, every time it finishes the run, it closes the debug window immediately with messages like this:

```
53909 Frames Processed
Commercials were found.
Close window when done
```

I using the latest, built myself from the github repo on Ubuntu 16.04.3 LTS

How can I actually get this to stay in the debug window?

**Comment by erikkaashoek** [comment]
Don't you see a windows appear with a black and white video?
Did you build with SDL library available?

**Comment by mjbrowns** [comment]
Yes I built it with SDL.

When I run:
```
comskip -w --ini=test.ini myvideo.mkv
```

the window opens and I can see the updates during processing but as soon as the processing completes, it exits and I don't have the ability to scan back and forth and look at the black frames, etc.  It exits immediately with the message above.

When I run
```
comskip -w myvideo.txt
```

The window opens and I get the black & white layout of the commercial cut points and can move around there.  That one doesn't immediately exit.  I don't quite get the usefulness of that yet but I suppose I'll get there.

**Comment by erikkaashoek** [comment]
You can navigate through the video using arrow, page up/down and by clicking on the timeline at the top
F1 will get you some  help

**Comment by mjbrowns** [comment]
Well, no i cant, because on the first run (above) it exits as soon as the detection finishes.

I'll put together a video/screen cap of what I'm experiencing and drop a link in here as soon as I can.

**Comment by mjbrowns** [comment]
ok, i've found the issue.

Frankly the documentation isn't terribly clear on whether or not the debug window should stay open when using -w on the initial comskip run on the source video file.

that said, what i've been doing in scripting is to create a symbolic link to my source file.  For example:
Source File:   my-video-file.mkv

ln -sf my-vido-file.mkv /working

then i can do the comskip [options] working

and all my output files are then consistently named working.<whatever>

It turns out when using:

comskip -w working.txt

it does not discover the original mkv file since my link name is just "working" rather than "working.mkv"

Changing the link name to include the file extension allows me to use comskip -w working.txt and I can see everything I need.

**Comment by erikkaashoek** [comment]
when using a .txt file as input you should not need to give -w option and comskip should find the recording file using a set of known extensions as long as the recording is in the same directory as the .txt file.
If the file does not have a known file extension it can not be found
