### ISSUE TITLE
Permission To Package In Fedora

### ISSUE THREAD

**Issue by mprahl** [erikkaashoek/Comskip#82]
Hello,
I would like to package comskip in Fedora so it could be installed by simply typing `dnf install comskip`. Would you have any objections to this?

If you're okay with it, may you please select a license to use for your repository? I will do the rest of the work.

Thank you very much for developing comskip. It is a great piece of software.

**Comment by erikkaashoek** [comment]
Current code as present on GitHub is GPL
OK to package as long is my name is mentioned as package maintainer, including a link to www.comskip.org

**Comment by mprahl** [comment]
Okay great. Could you please license your repository with GPL? You can read this documentation on how to do that: https://help.github.com/articles/licensing-a-repository/

**Comment by erikkaashoek** [comment]
Done
