### ISSUE TITLE
Speed Doubt

### ISSUE THREAD

**Issue by nicoparsa** [erikkaashoek/Comskip#85]
Hi,

By the first time, i would want to appreciate the work of the project. I have already use it and it's fantastic. Thanks you very much.

My goal is detect commercial breaks in h264 videos and I have a doubt related with the speed.

In my tests, I have seen that the speed in my Linux computer is ~80fps and I want to know if it's the maximum speed for this kind of video codec (h.264).

With other videos (MPEG2), the normal speed is approximately 600-800fps. 

If it's the normal speed, what do you recommend me for decrease the analysis time? Maybe decode the video to MPEG2?

Thanks you very much and I repeat, I appreciate your work very much.

**Comment by erikkaashoek** [comment]
Please have tuning discussions on http://www.kaashoek.com/comskip/index.php
This is only for code issues

**Comment by tmm1** [comment]
It seems there is some bug which causes H264 processing to be very slow on Linux (even in donator mode). The same commit compiled on windows or on mac is much faster.

**Comment by tmm1** [comment]
Never mind, I was mistaken. My mac/windows machines are faster than my linux one, so it wasn't a fair comparison.

One issue I noticed is that the `thread_count` setting affects both comskip threading and ffmpeg threading. If you want comskip to use only one thread, but ffmpeg to still use multiple threads for h264 decoding there's no easy way to do that.

**Comment by nicoparsa** [comment]
Hi Aman, what is the maximum processing speed (fps) that you had reach?

Can you share your machines specifications to compare?

Thank you so much!
