### ISSUE TITLE
configure.ac missing legacy source AM_PROG_CC_C_O

### ISSUE THREAD

**Issue by jaymichael78** [erikkaashoek/Comskip#86]
Please add this source to the configure.ac code. Or I can submit updated code if you let me know how you prefer someone else to make code changes.

> #add for legacy reasons.
AM_PROG_CC_C_O

**Comment by erikkaashoek** [comment]
Which line to insert at?

**Comment by jaymichael78** [comment]
I would place it immediately after AC_CANONICAL_HOST

# add for legacy reasons.
AM_PROG_CC_C_O

**Comment by tmm1** [comment]
What are the legacy reasons?

**Comment by jaymichael78** [comment]
It seems to be a reference at the end of the script to this. So I just made
the quickest change possible.

**Comment by tmm1** [comment]
There is no reference to CC_C_O that I can find in this repository.

If you're experiencing some sort of error, please post the error message along with the version of autoconf you are using.

**Comment by KKDad** [comment]
I got the exact same issue running on CentOS 7.4.1708:

> [kkdad@CloudServer Comskip]$ AUTORECONF=false ./autogen.sh
> Preparing the Comskip build system...please wait
> 
> Using AUTORECONF environment variable override: false
> Found GNU Autoconf version 2.69
> Found GNU Automake version 1.13.4
> Found GNU Libtool version 2.4.2
> 
> Automatically preparing build ... Warning: false failed
> Attempting to run the preparation steps individually
> 
> Preparing build ... automake: warnings are treated as errors
> Makefile.am:9: warning: compiling 'ccextratorwin/608.c' in subdir requires 'AM_PROG_CC_C_O' in 'configure.ac'
> ERROR: automake failed

I added AM_PROG_CC_C_O to configure.ac and this resolved the issue for me. 

Let me know and I can send you a PR

**Comment by tmm1** [comment]
Thank you for the full error message.

Please open a PR with the fix.
