### ISSUE TITLE
MacPorts-Failure

### ISSUE THREAD

**Issue by DebbieFL33** [erikkaashoek/Comskip#96]
In following your readme.md (Mac OS X):

I downloaded Macports and run "sudo port install ffmeg coreutils argtable:

Receive the following:

IMac-4:~ Debbie$ sudo port install ffmpeg coreutils argtable
--->  Computing dependencies for libpng
--->  Fetching archive for libpng
--->  Attempting to fetch libpng-1.6.34_1.darwin_16.x86_64.tbz2 from https://packages.macports.org/libpng
--->  Attempting to fetch libpng-1.6.34_1.darwin_16.x86_64.tbz2.rmd160 from https://packages.macports.org/libpng
--->  Installing libpng @1.6.34_1
--->  Cleaning libpng
--->  Computing dependencies for libpng
--->  Deactivating libpng @1.6.34_0
--->  Cleaning libpng
--->  Activating libpng @1.6.34_1
--->  Cleaning libpng
--->  Computing dependencies for ffmpeg
--->  Fetching archive for ffmpeg
Error: Failed to archivefetch ffmpeg: libsdl2 must be installed without +x11.
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_multimedia_ffmpeg/ffmpeg/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port ffmpeg failed

What else should I be doing?

My ultimate goal is to run comskip on a Qnap.  Am a total code newbie with no clue as to these processes, although I was able to run essandess etv-comskip (produced edl file) against EyeTV files when transcoding to iPad format.

**Comment by tmm1** [comment]
Use homebrew instead of macports. It's much easier.

Note that if you compile on your mac, that binary will only work on your mac and not other operating systems.

**Comment by DebbieFL33** [comment]
Ok, thanks @tmm1

**Comment by virtualdj** [comment]
> My ultimate goal is to run comskip on a Qnap.
Well, on the [QNAP forums](https://forum.qnap.com/viewtopic.php?f=276&t=120848&p=560344#p560344) you can find an already compiled version of Comskip for the QNAP (static build).

**Comment by DebbieFL33** [comment]
Thank you for the link.  I’ve replied on the Qnap forums.

Really appreciate your help
