### ISSUE TITLE
Installing on Debian Stretch (OSMC) fails with undeclared 'old' headers

### ISSUE THREAD

**Issue by wbeard52** [erikkaashoek/Comskip#97]
When installing Comskip on Debian Stretch (OSMC 2018.3), I got an error while compiling comskip-mpeg2dec.c.  The issue was with mpeg2dec.c file and the need to change the variable `CODEC_FLAG_GRAY` to `AV_CODEC_FLAG_GRAY`.  Afterwards, everything compiled and installed correctly.

**Comment by tmm1** [comment]
I believe this is already fixed on master.

**Comment by tmm1** [comment]
In https://github.com/erikkaashoek/Comskip/commit/1d987bde60b09db7dfbc1f0bf3f2096a370a4844

**Comment by wbeard52** [comment]
It may be but I downloaded the file git://github.com/IfThenERROR/Comskip and had to change that variable.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tmm1** [comment]
That version is not the official/latest, and is 9 months out of date.
