### ISSUE TITLE
Compilation fails with ffmpeg 3.5 on Fedora

### ISSUE THREAD

**Issue by mprahl** [erikkaashoek/Comskip#98]
Hello,
I'm in the process of packaging Comskip as an RPM for Fedora in the RPMFusion repo. It builds just fine on Fedora 27 which uses ffmpeg 3.3.6, but on Fedora 28, it fails while using ffmpeg 3.5. Any suggestions?

Here is the build log:
https://paste.fedoraproject.org/paste/LV-kjlXtL9aj9OJhr0UFOg

Thank you for your help.

**Comment by tmm1** [comment]
BUILDSTDERR: mpeg2dec.c: In function 'video_packet_process':
BUILDSTDERR: mpeg2dec.c:1202:5: warning: 'codec' is deprecated [-Wdeprecated-declarations]
BUILDSTDERR:      if (!hardware_decode) is->video_st->codec->flags |= CODEC_FLAG_GRAY;
BUILDSTDERR:      ^~

This issue is fixed on master.

**Comment by mprahl** [comment]
@tmm1 thank you. Pulling in a few patches from master worked. Are you planning to make another release soon? I'd prefer to use that rather than carry the patches on top of v0.82.003.
